# name: My first WorkFlow
# on: push

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print message
#         run: echo "Hello, Github Action!"



name: My first WorkFlow
on:
 push:
 pull_request:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print my name
        run: |
          echo "Hello, Shubham!"
          echo "shubham"


  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: Print by message
        run: |
          echo "bye, Shubham!"
          echo "shubham"